image: node:lts-alpine

stages:
  - build
  - package

cache:
  paths:
    - node_modules/**

build:
  stage: build
  script:
    - apk add --no-cache gcc musl-dev pkgconf gtk4.0-dev dpkg
    - gcc `pkg-config --cflags gtk4` -o theme-manager theme-manager.c `pkg-config --libs gtk4`
    - mkdir dist && mv theme-manager dist/ && mv favicon.svg dist/ && mv theme-manager.desktop dist/
    - tar -czf theme-manager.tar.gz -C dist .
  artifacts:
    name: "theme-manager-release_$CI_COMMIT_REF_SLUG"
    paths:
      - dist/
    expire_in: 1 week

package:
  stage: package
  script:
    - mkdir -p debian/usr/bin debian/usr/share/icons/hicolor/256x256/apps debian/usr/share/applications
    - cp theme-manager debian/usr/bin/
    - cp favicon.svg debian/usr/share/icons/hicolor/256x256/apps/theme-manager.svg
    - cp theme-manager.desktop debian/usr/share/applications/
    - dpkg-deb --build debian theme-manager.deb
    - makepkg
  artifacts:
    name: "theme-manager-release_$CI_COMMIT_REF_SLUG"
    paths:
      - debian/
      - theme-manager-*.pkg.tar.*
    expire_in: 1 week